[package]
name = "graph"
version = "0.1.0"
authors = ["Paulo Jorge PM <paulo.jorge.pm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxigraph = "0.2.5"
